fix GitHub Actions test workflows
New release github_changelog_generator v1.16.0 causing this problem:

    pdk (INFO): Using Ruby 2.7.2
    pdk (INFO): Using Puppet 7.4.1
    pdk (ERROR): The spec_clean rake task failed with the following error(s):

    rake aborted!
    ArgumentError: wrong number of arguments (given 1, expected 0)
    /home/runner/.pdk/cache/ruby/2.7.0/gems/github_changelog_generator-1.16.0/lib/github_changelog_generator/task.rb:34:in `initialize'
    /home/runner/.pdk/cache/ruby/2.7.0/gems/github_changelog_generator-1.16.0/lib/github_changelog_generator/task.rb:34:in `initialize'
    /home/runner/work/puppet-bind/puppet-bind/Rakefile:47:in `new'
    /home/runner/work/puppet-bind/puppet-bind/Rakefile:47:in `<top (required)>'
    /opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'

So had to switch acceptance tests to a native PDK install and remove
the github_changelog_generator gem.